#! /usr/bin/perl -w
use strict;

# Handles special characters at the end of input

while( my $input = <> ) {
	chomp($input);
	if ($input eq 'exit') {
		exit;
	}
	if ($input =~ /(^[aeiou]\w+\W?)/) {
		print "$1way\n";
	} 
	if ($input =~ /(^[^aeiou])(\w+)(\W?)/) {
		print "$2$3$1ay\n";
	}
}

exit;
